[catppuccin-prismlauncher]
src.git = "https://github.com/catppuccin/prismlauncher.git"
fetch.github = "catppuccin/prismlauncher"

[catppuccin-fuzzel]
src.git = "https://github.com/catppuccin/fuzzel.git"
fetch.github = "catppuccin/fuzzel"

# Provides GRUB wallpaper
[catppuccin-wallpapers]
src.git = "https://github.com/zhichaoh/catppuccin-wallpapers.git"
fetch.github = "zhichaoh/catppuccin-wallpapers"

# For vinegar overlay
[roblox-oof]
src.manual = "latest"
fetch.url = "https://archive.org/download/savetheoof/ouch.ogg"

# Fish plugins
[fish-bd]
src.git = "https://github.com/0rax/fish-bd.git"
fetch.github = "0rax/fish-bd"

[plugin-sudope]
src.git = "https://github.com/oh-my-fish/plugin-sudope.git"
fetch.github = "oh-my-fish/plugin-sudope"

[you-should-use]
src.git = "https://github.com/paysonwallach/fish-you-should-use.git"
fetch.github = "paysonwallach/fish-you-should-use"

# Nyxt plugins
[nx-fruit]
src.git = "https://github.com/atlas-engineer/nx-fruit.git"
fetch.github = "atlas-engineer/nx-fruit"

[nx-search-engines]
src.git = "https://github.com/aartaka/nx-search-engines.git"
fetch.github = "aartaka/nx-search-engines"

[nx-router]
src.manual = "0.2.0" # Source does not support shallow clone, which is needed to fetch version
fetch.git = "https://git.migalmoreno.com/nx-router"
git.deepClone = true
git.leaveDotGit = true # Required for deepClone

[nx-dark-reader]
src.git = "https://github.com/aartaka/nx-dark-reader.git"
fetch.github = "aartaka/nx-dark-reader"

# Nyxt rss reader
[demeter]
src.manual = "0.1.0"
fetch.url = "https://nyxt.atlas.engineer/static/release/demeter.tar.gz"

# xplr plugins
## Extension
[context-switch-xplr]
src.git = "https://github.com/igorepst/context-switch.xplr.git"
fetch.github = "igorepst/context-switch.xplr"

[offline-docs-xplr]
src.git = "https://github.com/sayanarijit/offline-docs.xplr.git"
fetch.github = "sayanarijit/offline-docs.xplr"

[tri-pane-xplr]
src.git = "https://github.com/sayanarijit/tri-pane.xplr.git"
fetch.github = "sayanarijit/tri-pane.xplr"

[type-to-nav-xplr]
src.git = "https://github.com/sayanarijit/type-to-nav.xplr.git"
fetch.github = "sayanarijit/type-to-nav.xplr"

[wl-clipboard-xplr]
src.git = "https://github.com/sayanarijit/wl-clipboard.xplr.git"
fetch.github = "sayanarijit/wl-clipboard.xplr"

[style-xplr]
src.git = "https://github.com/emsquid/style.xplr.git"
fetch.github = "emsquid/style.xplr"

## Integration
[dragon-xplr]
src.git = "https://github.com/sayanarijit/dragon.xplr.git"
fetch.github = "sayanarijit/dragon.xplr"

[dua-cli-xplr]
src.git = "https://github.com/sayanarijit/dua-cli.xplr.git"
fetch.github = "sayanarijit/dua-cli.xplr"

[fzf-xplr]
src.git = "https://github.com/sayanarijit/fzf.xplr.git"
fetch.github = "sayanarijit/fzf.xplr"

[ouch-xplr]
src.git = "https://github.com/dtomvan/ouch.xplr.git"
fetch.github = "dtomvan/ouch.xplr"

[scp-xplr]
src.git = "https://github.com/sayanarijit/scp.xplr.git"
fetch.github = "sayanarijit/scp.xplr"

[zoxide-xplr]
src.git = "https://github.com/sayanarijit/zoxide.xplr.git"
fetch.github = "sayanarijit/zoxide.xplr"

## Theme
[icons-xplr]
# Move to main repo after icons.xplr#4 is merged
# src.git = "https://github.com/prncss-xyz/icons.xplr.git"
# fetch.github = "prncss-xyz/icons.xplr"
src.branch = "nerfonts-v3-update"
src.git = "https://github.com/jbms/icons.xplr.git"
fetch.github = "jbms/icons.xplr"

[extra-icons-xplr]
src.git = "https://github.com/dtomvan/extra-icons.xplr.git"
fetch.github = "dtomvan/extra-icons.xplr"

# Animated wallpaper
# https://valenberg.tumblr.com/post/142420848259/animated-banner-artwork-for-the-great-rolly
[wallpaper]
src.manual = "latest"
fetch.url = "https://64.media.tumblr.com/c5543874b9cbe98da1d20945a45e989b/tumblr_o5a5r9Z9O71tvppquo1_r1_1280.gifv"
