[catppuccin-prismlauncher]
src.git = "https://github.com/catppuccin/prismlauncher.git"
fetch.github = "catppuccin/prismlauncher"

[catppuccin-fuzzel]
src.git = "https://github.com/catppuccin/fuzzel.git"
fetch.github = "catppuccin/fuzzel"

# Provides GRUB wallpaper
[catppuccin-fractal-wallpapers]
src.git = "https://github.com/psylopneunonym/Catppuccin-Fractal-Wallpapers.git"
fetch.github = "psylopneunonym/Catppuccin-Fractal-Wallpapers"

# For vinegar overlay
[roblox-oof]
src.manual = "latest"
fetch.url = "https://archive.org/download/savetheoof/ouch.ogg"

# Fish plugins
[fish-bd]
src.git = "https://github.com/0rax/fish-bd.git"
fetch.github = "0rax/fish-bd"

[plugin-sudope]
src.git = "https://github.com/oh-my-fish/plugin-sudope.git"
fetch.github = "oh-my-fish/plugin-sudope"

[you-should-use]
src.git = "https://github.com/paysonwallach/fish-you-should-use.git"
fetch.github = "paysonwallach/fish-you-should-use"

# Nyxt plugins
[nx-fruit]
src.git = "https://github.com/atlas-engineer/nx-fruit.git"
fetch.github = "atlas-engineer/nx-fruit"

[nx-search-engines]
src.git = "https://github.com/aartaka/nx-search-engines.git"
fetch.github = "aartaka/nx-search-engines"

[nx-router]
src.manual = "0.2.0" # Source does not support shallow clone, which is needed to fetch version
fetch.git = "https://git.migalmoreno.com/nx-router"
git.deepClone = true
git.leaveDotGit = true # Required for deepClone

[nx-dark-reader]
src.git = "https://github.com/aartaka/nx-dark-reader.git"
fetch.github = "aartaka/nx-dark-reader"

# Nyxt rss reader
[demeter]
src.manual = "0.1.0"
fetch.url = "https://nyxt.atlas.engineer/static/release/demeter.tar.gz"

# yazi plugins
## Previewers
[glow-yazi]
src.git = "https://github.com/Reledia/glow.yazi.git"
fetch.github = "Reledia/glow.yazi"

[miller-yazi]
src.git = "https://github.com/Reledia/miller.yazi.git"
fetch.github = "Reledia/miller.yazi"

[exifaudio-yazi]
src.git = "https://github.com/Sonico98/exifaudio.yazi.git"
fetch.github = "Sonico98/exifaudio.yazi"

[ouch-yazi]
src.git = "https://github.com/ndtoan96/ouch.yazi.git"
fetch.github = "ndtoan96/ouch.yazi"

## Functional Plugins
### Jumping
[relative-motions-yazi]
src.git = "https://github.com/dedukun/relative-motions.yazi.git"
fetch.github = "dedukun/relative-motions.yazi"

### filter enhancements
[yazi-plugins] # Has smart-filter.yazi
src.git = "https://github.com/yazi-rs/plugins.git"
fetch.github = "yazi-rs/plugins"

### UI enhancements
[starship-yazi]
src.git = "https://github.com/Rolv-Apneseth/starship.yazi.git"
fetch.github = "Rolv-Apneseth/starship.yazi"

## Utilities
[icons-brew-yazi]
src.git = "https://github.com/lpnh/icons-brew.yazi.git"
fetch.github = "lpnh/icons-brew"
