#!/usr/bin/env bash

# .config/yadm/bootstrap
# Bootstrap script intended to automate setting up a new hyper-personalized system
# WARNING: Only tested with EndeavourOS. May still work with other Arch derivatives, but NOT guaranteed.

# Dependencies for my setup for various programs
# Intended to be redundant so I don't have to consider if other programs
# already rely on something before adding or removing it.

# Dependencies for zsh config
zsh_deps=(
	"bat"
	"bat-extras"
	"dust"
	"exa"
	"fd"
	"fzf"
	"lolcat"
	"otf-nerd-fonts-fira-code"
	"pkgfile"
	"ripgrep" # Required by bat-extras
	"toilet"
	"toilet-fonts" # Required by toilet
	"wezterm"
	"zoxide"
	"zsh"
)

python_dev=(
	"flake8"
	"python"
	"python-language-server"
	"yapf"
)

haskell_dev=(
	"cabal-install"
	"ghc"
	"haskell-language-server"
	"haskell-ormolu"
	"hlint"
	"stack"
)

bash_dev=(
	"shellcheck"
	"shfmt"
)

common_lisp_dev=(
	"clisp"
	"sbcl"
)

# Dependencies for Kakoune setup
kak_deps=(
	"${bash_dev[@]}"
	"${common_lisp_dev[@]}"
	"${haskell_dev[@]}"
	"${python_dev[@]}"
	"clang" # For C development
	"fzf"
	"kakoune"
	"rustup" # For Rust development
)

# Miscellanious programs that I frequently use
misc=(
	"breeze-hacked-cursor-theme"
	"discord"
	"gnuplot" # Required by qalculate-gtk
	"itch"
	"joplin-desktop"
	"keepassxc"
	"lutris"
	"megasync"
	"moreutils"
	"qalculate-gtk"
	"steam"
	"strawberry"
	"syncthing"
	"syncthingtray"
	"tealdeer"
	"waterfox-g3-bin"
	"wine"
	"wine-gecko"
	"wine-mono"
	"yubioath-desktop"
)

# Install programs with yay
yay -Syu --needed $(echo "${zsh_deps[*]} ${kak_deps[*]} ${misc[*]}" | sort | uniq)

# Switch user's default shell to zsh
if chsh -s "$(which zsh)"; then
	echo "Successfully set $USER's shell to zsh"
else
	echo "Could not set $USER's shell to zsh"
fi

# Set cursor theme in default theme
default_cursor_theme="/usr/share/icons/default/index.theme"

if sudo sed -i "s/Adwaita/Breeze_Hacked/" "$default_cursor_theme"; then
	echo "Successfully set cursor in $default_cursor_theme"
else
	echo "Could not set cursor in $default_cursor_theme"
fi

# Download color scheme to KDE home directory
color_scheme_url="https://raw.githubusercontent.com/Roboron3042/Cyberpunk-Neon/master/kde/cyberpunk-neon.colors"
color_scheme_dir="$HOME/.local/share/color-schemes/"

if mkdir -p "$color_scheme_dir"; then
	if wget "$color_scheme_url" --output-document="$color_scheme_dir/cyberpunk-neon.colors"; then
		echo "Successfully downloaded KDE color scheme"
	else
		echo "Could not download KDE color scheme"
	fi
else
	echo "Could not create folder at $color_scheme_dir"
fi

# Install and configure icon theme
if wget -qO- https://raw.githubusercontent.com/gusbemacbe/suru-plus-aspromauros/master/install.sh | sh; then
	echo "Successfully installed icon theme"

	if sudo mv /usr/share/icons/Suru++-Asprómauros /usr/share/icons/Suru++; then
		echo "Successfully renamed icon theme folder"

		if sudo wget https://git.io/fhbxw --output-document="/usr/local/bin/suru-plus-colourise"; then
			if sudo chmod a+x /usr/local/bin/suru-plus-colourise; then
				echo "Successfully installed suru-plus-colourise"
				sudo suru-plus-colourise
			else
				echo "Could not install suru-plus-colourise"
			fi
		else
			echo "Could not install suru-plus-colourise"
		fi
	else
		echo "Could not rename icon theme folder"
	fi
else
	echo "Could not install icon theme"
fi

# TODO: Install GRUB theme

# TODO: Configure rustup

# TODO: Install and configure betterdiscord

# TODO: Initialize QMK

# TODO: Configure QEMU

# TODO: Enable pkgfile service

# TODO: Prompt instructions for remaining manual setup
