# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catppuccin-fractal-wallpapers = {
    pname = "catppuccin-fractal-wallpapers";
    version = "cd439e85eb5b81808e5f6dc64adb2c171fc0853f";
    src = fetchFromGitHub {
      owner = "psylopneunonym";
      repo = "Catppuccin-Fractal-Wallpapers";
      rev = "cd439e85eb5b81808e5f6dc64adb2c171fc0853f";
      fetchSubmodules = false;
      sha256 = "sha256-udMkIX5etmRR0O+MPWeDAMZH4BW0YS0pDUE0wcwszQI=";
    };
    date = "2022-08-18";
  };
  catppuccin-fuzzel = {
    pname = "catppuccin-fuzzel";
    version = "125dc68ba79ddfe71e59412257698418c4f05218";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fuzzel";
      rev = "125dc68ba79ddfe71e59412257698418c4f05218";
      fetchSubmodules = false;
      sha256 = "sha256-ut46aEuBdMekkuB72Va3snR9q5tmRLQvYIC4E6rjbYs=";
    };
    date = "2024-07-26";
  };
  catppuccin-prismlauncher = {
    pname = "catppuccin-prismlauncher";
    version = "2edbdf5295bc3c12c3dd53b203ab91028fce2c54";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "prismlauncher";
      rev = "2edbdf5295bc3c12c3dd53b203ab91028fce2c54";
      fetchSubmodules = false;
      sha256 = "sha256-+yGrSZztf2sZ9frPT3ydIJDavo4eXs03cQWfdTAmn3w=";
    };
    date = "2024-06-11";
  };
  exifaudio-yazi = {
    pname = "exifaudio-yazi";
    version = "92366cf0b024a05cb80c9e245408026dcabe94f2";
    src = fetchFromGitHub {
      owner = "Sonico98";
      repo = "exifaudio.yazi";
      rev = "92366cf0b024a05cb80c9e245408026dcabe94f2";
      fetchSubmodules = false;
      sha256 = "sha256-QAIUwArdMvTxSRTXDg72rk1E2JresC4KzADqIPXnKLE=";
    };
    date = "2024-06-30";
  };
  fish-bd = {
    pname = "fish-bd";
    version = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
    src = fetchFromGitHub {
      owner = "0rax";
      repo = "fish-bd";
      rev = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
      fetchSubmodules = false;
      sha256 = "sha256-GeWjoakXa0t2TsMC/wpLEmsSVGhHFhBVK3v9eyQdzv0=";
    };
    date = "2022-03-04";
  };
  glow-yazi = {
    pname = "glow-yazi";
    version = "536185a4e60ac0adc11d238881e78678fdf084ff";
    src = fetchFromGitHub {
      owner = "Reledia";
      repo = "glow.yazi";
      rev = "536185a4e60ac0adc11d238881e78678fdf084ff";
      fetchSubmodules = false;
      sha256 = "sha256-NcMbYjek99XgWFlebU+8jv338Vk1hm5+oW5gwH+3ZbI=";
    };
    date = "2024-05-02";
  };
  icons-brew-yazi = {
    pname = "icons-brew-yazi";
    version = "b72dff8c252154f99bb8ea16305f94fc79978614";
    src = fetchFromGitHub {
      owner = "lpnh";
      repo = "icons-brew";
      rev = "b72dff8c252154f99bb8ea16305f94fc79978614";
      fetchSubmodules = false;
      sha256 = "sha256-5ptPcsMPFA/uN7JV1T87K61m7ddM9+vPKwbEEw8xz0M=";
    };
    date = "2024-06-14";
  };
  miller-yazi = {
    pname = "miller-yazi";
    version = "75f00026a0425009edb6fedcfbe893f3d2ddedf4";
    src = fetchFromGitHub {
      owner = "Reledia";
      repo = "miller.yazi";
      rev = "75f00026a0425009edb6fedcfbe893f3d2ddedf4";
      fetchSubmodules = false;
      sha256 = "sha256-u8xadj6/s16xXUAWGezYBqnygKaFMnRUsqtjMDr6DZA=";
    };
    date = "2024-05-02";
  };
  ouch-yazi = {
    pname = "ouch-yazi";
    version = "251da6930ca8b7ee0384810086c3bf644caede3e";
    src = fetchFromGitHub {
      owner = "ndtoan96";
      repo = "ouch.yazi";
      rev = "251da6930ca8b7ee0384810086c3bf644caede3e";
      fetchSubmodules = false;
      sha256 = "sha256-yLt9aY6hUIOdBI5bMdCs7VYFJGyD3WIkmPxvWKNCskA=";
    };
    date = "2024-07-15";
  };
  plugin-sudope = {
    pname = "plugin-sudope";
    version = "83919a692bc1194aa322f3627c859fecace5f496";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-sudope";
      rev = "83919a692bc1194aa322f3627c859fecace5f496";
      fetchSubmodules = false;
      sha256 = "sha256-pD4rNuqg6TG22L9m8425CO2iqcYm8JaAEXIVa0H/v/U=";
    };
    date = "2021-04-11";
  };
  relative-motions-yazi = {
    pname = "relative-motions-yazi";
    version = "73f554295f4b69756597c9fe3caf3750a321acea";
    src = fetchFromGitHub {
      owner = "dedukun";
      repo = "relative-motions.yazi";
      rev = "73f554295f4b69756597c9fe3caf3750a321acea";
      fetchSubmodules = false;
      sha256 = "sha256-jahJC6LXOnr974+zHEH9gqI+J1C68O+PvjSt8pelkP0=";
    };
    date = "2024-07-19";
  };
  roblox-oof = {
    pname = "roblox-oof";
    version = "latest";
    src = fetchurl {
      url = "https://archive.org/download/savetheoof/ouch.ogg";
      sha256 = "sha256-vcxbfljNxTFS+uFxrV/zKdDWWBBYN2hJIwkN5MN8AH0=";
    };
  };
  starship-yazi = {
    pname = "starship-yazi";
    version = "0a141f6dd80a4f9f53af8d52a5802c69f5b4b618";
    src = fetchFromGitHub {
      owner = "Rolv-Apneseth";
      repo = "starship.yazi";
      rev = "0a141f6dd80a4f9f53af8d52a5802c69f5b4b618";
      fetchSubmodules = false;
      sha256 = "sha256-OL4kSDa1BuPPg9N8QuMtl+MV/S24qk5R1PbO0jgq2rA=";
    };
    date = "2024-07-16";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "06e5fe1c7a2a4009c483b28b298700590e7b6784";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "06e5fe1c7a2a4009c483b28b298700590e7b6784";
      fetchSubmodules = false;
      sha256 = "sha256-jg8+GDsHOSIh8QPYxCvMde1c1D9M78El0PljSerkLQc=";
    };
    date = "2024-07-18";
  };
  you-should-use = {
    pname = "you-should-use";
    version = "a332823512c0b51e71516ebb8341db0528c87926";
    src = fetchFromGitHub {
      owner = "paysonwallach";
      repo = "fish-you-should-use";
      rev = "a332823512c0b51e71516ebb8341db0528c87926";
      fetchSubmodules = false;
      sha256 = "sha256-MmGDFTgxEFgHdX95OjH3jKsVG1hdwo6bRht+Lvvqe5Y=";
    };
    date = "2022-02-13";
  };
}
