# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catppuccin-fractal-wallpapers = {
    pname = "catppuccin-fractal-wallpapers";
    version = "cd439e85eb5b81808e5f6dc64adb2c171fc0853f";
    src = fetchFromGitHub {
      owner = "psylopneunonym";
      repo = "Catppuccin-Fractal-Wallpapers";
      rev = "cd439e85eb5b81808e5f6dc64adb2c171fc0853f";
      fetchSubmodules = false;
      sha256 = "sha256-udMkIX5etmRR0O+MPWeDAMZH4BW0YS0pDUE0wcwszQI=";
    };
    date = "2022-08-18";
  };
  catppuccin-fuzzel = {
    pname = "catppuccin-fuzzel";
    version = "eeb4c8d159187ef7eb59a4a99baec67c2e797e9f";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fuzzel";
      rev = "eeb4c8d159187ef7eb59a4a99baec67c2e797e9f";
      fetchSubmodules = false;
      sha256 = "sha256-yJvhc4ovgdxEdqFDxWNOkHJHTBF9UaCefetgCGhoG0A=";
    };
    date = "2024-01-24";
  };
  catppuccin-prismlauncher = {
    pname = "catppuccin-prismlauncher";
    version = "07e9c3ca0ff8eb7da9fa8b5329a9d2ceec707f24";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "prismlauncher";
      rev = "07e9c3ca0ff8eb7da9fa8b5329a9d2ceec707f24";
      fetchSubmodules = false;
      sha256 = "sha256-/qUqF92e3kYkl59GUMMFRtRTzVgSp5tGPxnXLGeusys=";
    };
    date = "2024-03-30";
  };
  demeter = {
    pname = "demeter";
    version = "0.1.0";
    src = fetchurl {
      url = "https://nyxt.atlas.engineer/static/release/demeter.tar.gz";
      sha256 = "sha256-XjgI0F2QVwV2KSH+7eO3G1lX/NZ6hXPYztCIlXdnOJc=";
    };
  };
  exifaudio-yazi = {
    pname = "exifaudio-yazi";
    version = "94329ead8b3a6d3faa2d4975930a3d0378980c7a";
    src = fetchFromGitHub {
      owner = "Sonico98";
      repo = "exifaudio.yazi";
      rev = "94329ead8b3a6d3faa2d4975930a3d0378980c7a";
      fetchSubmodules = false;
      sha256 = "sha256-jz6fVtcLHw9lsxFWECbuxE7tEBttE08Fl4oJSTifaEc=";
    };
    date = "2024-02-28";
  };
  fish-bd = {
    pname = "fish-bd";
    version = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
    src = fetchFromGitHub {
      owner = "0rax";
      repo = "fish-bd";
      rev = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
      fetchSubmodules = false;
      sha256 = "sha256-GeWjoakXa0t2TsMC/wpLEmsSVGhHFhBVK3v9eyQdzv0=";
    };
    date = "2022-03-04";
  };
  glow-yazi = {
    pname = "glow-yazi";
    version = "536185a4e60ac0adc11d238881e78678fdf084ff";
    src = fetchFromGitHub {
      owner = "Reledia";
      repo = "glow.yazi";
      rev = "536185a4e60ac0adc11d238881e78678fdf084ff";
      fetchSubmodules = false;
      sha256 = "sha256-NcMbYjek99XgWFlebU+8jv338Vk1hm5+oW5gwH+3ZbI=";
    };
    date = "2024-05-02";
  };
  icons-brew-yazi = {
    pname = "icons-brew-yazi";
    version = "b72dff8c252154f99bb8ea16305f94fc79978614";
    src = fetchFromGitHub {
      owner = "lpnh";
      repo = "icons-brew";
      rev = "b72dff8c252154f99bb8ea16305f94fc79978614";
      fetchSubmodules = false;
      sha256 = "sha256-5ptPcsMPFA/uN7JV1T87K61m7ddM9+vPKwbEEw8xz0M=";
    };
    date = "2024-06-14";
  };
  miller-yazi = {
    pname = "miller-yazi";
    version = "75f00026a0425009edb6fedcfbe893f3d2ddedf4";
    src = fetchFromGitHub {
      owner = "Reledia";
      repo = "miller.yazi";
      rev = "75f00026a0425009edb6fedcfbe893f3d2ddedf4";
      fetchSubmodules = false;
      sha256 = "sha256-u8xadj6/s16xXUAWGezYBqnygKaFMnRUsqtjMDr6DZA=";
    };
    date = "2024-05-02";
  };
  nx-dark-reader = {
    pname = "nx-dark-reader";
    version = "57dc1a9482a81d7c15b00c4b9d647bf1b129d8e4";
    src = fetchFromGitHub {
      owner = "aartaka";
      repo = "nx-dark-reader";
      rev = "57dc1a9482a81d7c15b00c4b9d647bf1b129d8e4";
      fetchSubmodules = false;
      sha256 = "sha256-CKJGCk7ATd0naFhill5rrvay6V2JE4Bstu4tFpaAjB0=";
    };
    date = "2023-06-20";
  };
  nx-fruit = {
    pname = "nx-fruit";
    version = "161856d20bccec729a43767bd926aca2e651f100";
    src = fetchFromGitHub {
      owner = "atlas-engineer";
      repo = "nx-fruit";
      rev = "161856d20bccec729a43767bd926aca2e651f100";
      fetchSubmodules = false;
      sha256 = "sha256-mLZ/1LagwsdTj/qOxqTOu3OP6pwByO0ITfwxi547qeg=";
    };
    date = "2024-01-03";
  };
  nx-router = {
    pname = "nx-router";
    version = "0.2.0";
    src = fetchgit {
      url = "https://git.migalmoreno.com/nx-router";
      rev = "0.2.0";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-H4v90ujqZJaigEodz5d8fr1qKcbIyxzN9sUiy9qkwbA=";
    };
  };
  nx-search-engines = {
    pname = "nx-search-engines";
    version = "f81f47df82f8e322f0a8919d05fc513297095a0b";
    src = fetchFromGitHub {
      owner = "aartaka";
      repo = "nx-search-engines";
      rev = "f81f47df82f8e322f0a8919d05fc513297095a0b";
      fetchSubmodules = false;
      sha256 = "sha256-Q+6B3lDzlhfHnS306yLh5LpxdIXESdH/Y2D3GJodbXs=";
    };
    date = "2023-06-07";
  };
  ouch-yazi = {
    pname = "ouch-yazi";
    version = "694d149be5f96eaa0af68d677c17d11d2017c976";
    src = fetchFromGitHub {
      owner = "ndtoan96";
      repo = "ouch.yazi";
      rev = "694d149be5f96eaa0af68d677c17d11d2017c976";
      fetchSubmodules = false;
      sha256 = "sha256-J3vR9q4xHjJt56nlfd+c8FrmMVvLO78GiwSNcLkM4OU=";
    };
    date = "2024-03-26";
  };
  plugin-sudope = {
    pname = "plugin-sudope";
    version = "83919a692bc1194aa322f3627c859fecace5f496";
    src = fetchFromGitHub {
      owner = "oh-my-fish";
      repo = "plugin-sudope";
      rev = "83919a692bc1194aa322f3627c859fecace5f496";
      fetchSubmodules = false;
      sha256 = "sha256-pD4rNuqg6TG22L9m8425CO2iqcYm8JaAEXIVa0H/v/U=";
    };
    date = "2021-04-11";
  };
  relative-motions-yazi = {
    pname = "relative-motions-yazi";
    version = "e223bce4bd2d6b558bbb4660768449a3087f8eb4";
    src = fetchFromGitHub {
      owner = "dedukun";
      repo = "relative-motions.yazi";
      rev = "e223bce4bd2d6b558bbb4660768449a3087f8eb4";
      fetchSubmodules = false;
      sha256 = "sha256-gd7xrSx0V0ZvDpSrqrNgnAXQn9LlF10myWRoAOZzxak=";
    };
    date = "2024-05-15";
  };
  roblox-oof = {
    pname = "roblox-oof";
    version = "latest";
    src = fetchurl {
      url = "https://archive.org/download/savetheoof/ouch.ogg";
      sha256 = "sha256-vcxbfljNxTFS+uFxrV/zKdDWWBBYN2hJIwkN5MN8AH0=";
    };
  };
  starship-yazi = {
    pname = "starship-yazi";
    version = "6197e4cca4caed0121654079151632f6abcdcae9";
    src = fetchFromGitHub {
      owner = "Rolv-Apneseth";
      repo = "starship.yazi";
      rev = "6197e4cca4caed0121654079151632f6abcdcae9";
      fetchSubmodules = false;
      sha256 = "sha256-oHoBq7BESjGeKsaBnDt0TXV78ggGCdYndLpcwwQ8Zts=";
    };
    date = "2024-04-03";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "db660364e92235a272718015292ac579db651d67";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "db660364e92235a272718015292ac579db651d67";
      fetchSubmodules = false;
      sha256 = "sha256-7xpjC86wtRSOvFBZZqR/3iZjtphwLYZtbrRG5Clhjtk=";
    };
    date = "2024-06-14";
  };
  you-should-use = {
    pname = "you-should-use";
    version = "a332823512c0b51e71516ebb8341db0528c87926";
    src = fetchFromGitHub {
      owner = "paysonwallach";
      repo = "fish-you-should-use";
      rev = "a332823512c0b51e71516ebb8341db0528c87926";
      fetchSubmodules = false;
      sha256 = "sha256-MmGDFTgxEFgHdX95OjH3jKsVG1hdwo6bRht+Lvvqe5Y=";
    };
    date = "2022-02-13";
  };
}
