add-highlighter global/ number-lines -hlcursor

# Source plug.kak
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload

plug "ul/kak-lsp" do %{
    cargo install --locked --force --path .
} config %{
    # Cool unicode indicators
    set-option global lsp_diagnostic_line_error_sign "✖"
    set-option global lsp_diagnostic_line_warning_sign "➤"

    # Enable lsp
    lsp-enable

    # Format on save
    hook global WinSetOption filetype=(haskell|rust) %{
        hook buffer BufWritePre .* lsp-formatting-sync
    }
    #    set-option global lsp_hover_max_lines 10
}

hook global WinSetOption filetype=sh %{
    set-option window formatcmd "shfmt"
    hook buffer BufWritePre .* format
}

hook global WinSetOption filetype=c %{
    set-option window formatcmd 'clang-format --style="{IndentWidth: 4}"'
    hook buffer BufWritePre .* format
}

plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option global softtabstop 4
} config %{
    hook global WinSetOption filetype=(kak|bash|plain) .* smarttab
    hook global WinSetOption filetype=(c|haskell|rust|yaml) .* expandtab
}

# Highlight current line and/or current column
plug "insipx/kak-crosshairs" config %{
    crosshairs
}

# File tree navigator
plug "andreyorst/kaktree" defer kaktree %{
    set-option global kaktree_double_click_duration "0.5"
    set-option global kaktree_indentation 1
    set-option global kaktree_dir_icon_open  "▾ 🗁 "
    set-option global kaktree_dir_icon_close "▸ 🗀 "
    set-option global kaktree_file_icon      "⠀⠀🖺"
} config %{
    hook global WinSetOption filetype=kaktree %{
        remove-highlighter buffer/numbers
        remove-highlighter buffer/matching
        remove-highlighter buffer/wrap
        remove-highlighter buffer/show-whitespaces
    }#
    kaktree-enable
}

# Source my custom powerline theme
source "%val{config}/colors/cyberpunk-neon-powerline.kak"

# Powerline Bar
# TODO: Investigate creating a theme
plug "andreyorst/powerline.kak" defer powerline %{
    # Use my custom powerline theme
    powerline-theme cyberpunk-neon
    set-option global powerline_shorten_bufname short
    # Default layout
    #set-option global powerline_format "git bufname line-column mode-info filetype client session position"
} config %{
    powerline-start
}

# Pairing parentheses and brackets
plug "alexherbo2/auto-pairs.kak"

# Highlight recursive pairs of parentheses
# TODO: Configure faces
plug "JJK96/kakoune-rainbow"

# Search highlighter
plug "alexherbo2/search-highlighter.kak"

# fzf integration
plug "andreyorst/fzf.kak"

# Easy navigation of open buffers
plug "delapouite/kakoune-buffers" %{
    # Buffer user mode
    map global user b ": enter-buffers-mode<ret>" -docstring "buffers"
    map global user B ": enter-user-mode -lock buffers<ret>" -docstring "buffers (lock)"
}

# Preview faces in a colorscheme
plug "delapouite/kakoune-palette"

# Enhanced selections
plug "delapouite/kakoune-auto-percent"

# Enhanced searches
plug "delapouite/kakoune-auto-star"

# Tagbar browsing
plug "andreyorst/tagbar.kak" defer "tagbar" %{
    set-option global tagbar_sort false
    set-option global tagbar_size 40
    set-option global tagbar_display_anon false
} config %{
    # if you have wrap highlighter enamled in you configuration
    # files it"s better to turn it off for tagbar, using this hook:
    hook global WinSetOption filetype=tagbar %{
        remove-highlighter window/wrap
        # you can also disable rendering whitespaces here, line numbers, and
        # matching characters
    }
    # Automatically start tagbar on certain filetypes
    #hook global WinSetOption filetype=(css|html|haskell|rust) %{
        #tagbar-enable
    #}
}

# Manual indentation
plug "alexherbo2/manual-indent.kak" config %{
    hook global WinCreate .* %{
        manual-indent-enable
    }
}

# Surround selections with paired characters
# Is not affected by auto-pairs like kakoune-mirror is
plug "alexherbo2/surround.kak" config %{
    map global user s ": surround<ret>" -docstring "Enter surround mode"
    map global user S ": surround _ _ * *<ret>" -docstring "Enter surround mode with extra surrounding pairs"

    set-option global surround_begin auto-pairs-disable
    set-option global surround_end auto-pairs-enable
}

# Symmetrically grow/shrink horizontlly.
plug "delapouite/kakoune-mirror" config %{
    map global user m ": enter-user-mode -lock mirror<ret>" -docstring "Enter mirror mode"

    # Unmap surround commands.
    # Redundant with surround.kak
    # And vulnerable to weirdness with auto-pairs
    unmap global mirror (
    unmap global mirror {
    unmap global mirror [
    unmap global mirror <
    unmap global mirror )
    unmap global mirror }
    unmap global mirror ]
    unmap global mirror >
    unmap global mirror '"'
    unmap global mirror "'"
    unmap global mirror '`'
}

# Selects all adjavent lines that match the current selection
plug "occivink/kakoune-vertical-selection" config %{
#	map global user v ': vertical-selection-down<ret>' -docstring "Copy current selection downwards."
#	map global user ^ ': vertical-selection-up<ret>' -docstring "Copy current selection upwards."
#	map global user V ': vertical-selection-up-and-down<ret>' -docstring "Copy current selection upwards or downwards."
}

# Enhances text objects
# Depends on kakoune-vertical-selection
plug "delapouite/kakoune-text-objects" %{
    #text-object-map
    map global user <a-s> ": enter-user-mode selections<ret>" -docstring "selectors..."
}

# Roguelike-style light simulation
plug "occivink/kakoune-roguelight" config %{
    define-command roguelight-toggle %{
        try %{
            crosshairs
            roguelight-enable
        } catch %{
            roguelight-disable
        }

        hook -group roguelight window RawKey .* roguelight-refresh
 	}

    define-command roguelight-map %{
        edit -readonly "%val{config}/plugins/kakoune-roguelight/map"
        roguelight-toggle
    }
}

# Set colorscheme to custom one
colorscheme cyberpunk-neon

# Tabs are 4 characters long
set-option global tabstop 4

# Function Key Mapping

# Utilities
map global normal <F1> ": tagbar-enable<ret>"
map global normal <F2> ": tagbar-toggle<ret>"
map global normal <F3> ": fzf-mode<ret>"
map global normal <F4> ": kaktree-toggle<ret>"

# Info
map global normal <F5> ": info-buffers<ret>"
map global normal <F6> ": new buffer *debug*<ret>"

# Navigate to error
map global normal <F7> ": lsp-find-error --previous --include-warnings<ret>"
map global normal <F8> ": lsp-find-error --include-warnings<ret>"
map global normal <a-F7> ": lsp-find-error --previous<ret>"
map global normal <a-F8> ": lsp-find-error <ret>"

# Linting
unmap global normal <F9> ": tagbar-toggle<ret>"
map global normal <F9> ": lsp-hover<ret>"
map global normal <F10> ": new lsp-diagnostics<ret>"

# Exiting
map global normal <F11> ": delete-buffer<ret>"
map global normal <F12> ": quit<ret>"

# Alt + Number keymaps
# map global normal <a-1>
# map global normal <a-2>
# map global normal <a-3>
# map global normal <a-4>
# map global normal <a-5>
# map global normal <a-6>
# map global normal <a-7>
# map global normal <a-8>
# map global normal <a-9>
# map global normal <a-0>
