# Config for sworkstyle
#
# You can rename workspaces based on the exact application names or by generic pattern.
# When it could not match anything it will use the fallback.
#
# format:
#
# 	'{pattern}' = '{icon}'
#
# pattern: Can either be the exact "app_name" (app_id/class) of the window or a regex string in the format of `"/{regex}/"` which will match the window "title".
# icon: Your beatifull icon
#
# verbose format:
# 
#	'{pattern}' = { type = 'generic' | 'exact', value = '{icon}' }
#
#
# If it couldn't match something it will print:
# 
# WARN [sworkstyle:config] No match for '{app_name}' with title '{title}' 
#
# You can use {title} to do a generic matching 
# You can use {app_name} to do an exact match

fallback = ''

[matching]
'discord' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'thunderbird' = { type = 'generic', value = '' }
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'Spotify' = ''
'/(?i)Github.*Firefox/' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''

'org.wezfurlong.wezterm' = ''
'waterfox' = { type = 'generic', value = '' }
'thunar' = ''
'lutris' = ''
'org.keepassxc.KeePassXC' = ''
'FreeTube' = ''
'yubico.com.yubioath-desktop' = ''
'virt-manager' = ''
'/RuneLite.*/' = ''
'runescape' = { type = 'generic', value = '' }
'Grapejuice' = ''
'/Roblox.*/' = ''
'gdlauncher' = ''
'polkit-gnome-authentication-agent-1' = ''
'Timeshift-gtk' = ''
'itch' = ''
'imagewriter' = ''
'blueman-manager' = ''
'pavucontrol' = '墳'
'Joplin' = '﮶'
'org.kde.k3b' = ''
'siglo' = '愈'
'/Minecraft.*/' = ''
'/FML early loading progress/' = ''
'nyxt' = '爵'
'org.pwmt.zathura' = ''