[[language]]
name = "lua"
auto-format = true

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "python"
auto-format = true
config = """
{
  "pylsp": { 
    "plugins": {
      "black": {
        "enabled": true
        "line-length": 79
      }
    }
  }
}
"""

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "c"
indent = { tab-width = 4, unit = " " }
auto-format = true

[[language]]
name = "julia"
auto-format = true
