[[language]]
name = "bash"
language-server = { command = "efm-langserver" }

[[language]]
name = "lua"
language-server = { command = "lua-language-server" }

[[language]]
name = "haskell"
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
language-server = { command = "haskell-language-server-wrapper", args = ["--lsp"] }