[[language]]
name = "lua"
language-server = { command = "lua-language-server" }
auto-format = true

[[language]]
name = "haskell"
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
language-server = { command = "haskell-language-server-wrapper", args = ["lsp"] }

[[language]]
name = "python"
auto-format = true
config = """
{
  "pylsp": { 
    "plugins": {
      "black": {
        "enabled": true
        "line-length": 79
      }
    }
  }
}
"""

[[language]]
name = "markdown"
roots = [".marksman.toml"]
language-server = { command = "marksman", args=["server"] }
