[[language]]
name = "lua"
auto-format = true

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "python"
auto-format = true
config = """
{
  "pylsp": { 
    "plugins": {
      "black": {
        "enabled": true
        "line-length": 79
      }
    }
  }
}
"""

