[[language]]
name = "bash"
language-server = { command = "efm-langserver" }

[[language]]
name = "lua"
language-server = { command = "lua-language-server" }

[[language]]
name = "haskell"
scope = "source.haskell"
injection-regex = "haskell"
file-types = ["hs"]
roots = []
comment-token = "--"

indent = { tab-width = 2, unit = "  " }
language-server = { command = "haskell-language-server-wrapper", args = ["--lsp"] }